version: "3"
services:
  app:
    image: elixir:1.8.1
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: /bin/sh -c "cd /app && mix local.hex --force && mix deps.get && mix ecto.setup && mix phx.server"
    links:
      - db
    depends_on:
      - db
  db:
    image: "postgresql:11"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .db:/var/lib/postgresql/data